include:
  - component: $CI_SERVER_FQDN/home-lab/automations/docker-compose-service-deployment@v2.0.4
    inputs:
      vm-hostname: nas.srv.xbhl.intranet
      vm-ssh-username: $SSH_USER
      vm-ssh-private-key: $SSH_PRIVATE_KEY
      service-name: gatus
      container-name: gatus
      container-location: /share/Container/services/gatus
      cloudflare-dns-entry-name: status.intranet.xbhl.online
      cloudflare-zone-id: $CLOUDFLARE_ZONE_ID
      cloudflare-dns-api-token: $CLOUDFLARE_DNS_API_TOKEN
      container-healthcheck-delay: 180
      delete-existing-container-files: true

setup:generate-build-artifacts:
  script:
    - cp src/.env $BUILD_ARTIFACTS_DIR
    - sed -i "s|^GATUS_DOMAIN=.*|GATUS_DOMAIN=${SERVICE_HOSTNAME}|" $BUILD_ARTIFACTS_DIR/.env
    - sed -i "s|^GITLAB_STATUS_TOKEN=.*|GITLAB_STATUS_TOKEN=${GITLAB_STATUS_TOKEN}|" $BUILD_ARTIFACTS_DIR/.env
    - sed -i "s|^OPEN_WEBUI_AUTH_TOKEN=.*|OPEN_WEBUI_AUTH_TOKEN=${OPEN_WEBUI_AUTH_TOKEN}|" $BUILD_ARTIFACTS_DIR/.env
    - sed -i "s|^TAUTULLI_API_KEY=.*|TAUTULLI_API_KEY=${TAUTULLI_API_KEY}|" $BUILD_ARTIFACTS_DIR/.env
    # prepare busybox
    - mkdir -p $BUILD_ARTIFACTS_DIR/bin
    - wget https://www.busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox -O $BUILD_ARTIFACTS_DIR/bin/busybox
    - chmod +x $BUILD_ARTIFACTS_DIR/bin/busybox
    - $BUILD_ARTIFACTS_DIR/bin/busybox date # just to check
