metrics: true

ui:
  title: XBHL.online status
  header: XBHL.online
  dashboard-heading: Health dashboard
  dashboard-subheading: Real-time homelab services monitoring
  link: https://${GATUS_DOMAIN}
  default-sort-by: group

storage:
  type: postgres
  path: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
  caching: true
  maximum-number-of-results: 100
  maximum-number-of-events: 50
