pve-direct-api-template: &pve-direct-api-template
  group: proxmox
  interval: 30s
  client:
    insecure: true
  headers:
    Authorization: "PVEAPIToken=${PVE_API_TOKEN}"
  conditions:
    - "[STATUS] == 200"

pbs-direct-api-template: &pbs-direct-api-template
  group: proxmox
  interval: 30s
  client:
    insecure: true
  headers:
    Authorization: "PBSAPIToken=${PBS_API_TOKEN}"
  conditions:
    - "[STATUS] == 200"

endpoints:
  # Proxmox Virtual Environment
  - name: pve-01-machine-status
    <<: *pve-direct-api-template
    url: "https://pve01.srv.xbhl.intranet:8006/api2/json/nodes/pve-01/status"

  - name: pve-02-machine-status
    <<: *pve-direct-api-template
    url: "https://pve02.srv.xbhl.intranet:8006/api2/json/nodes/pve-02/status"

  - name: pve-main-gateway-status
    group: proxmox
    interval: 30s    
    headers:
      Authorization: "PVEAPIToken=${PVE_API_TOKEN}"
    url: "https://pve.intranet.xbhl.online/api2/json/nodes"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  # Proxmox Backup Server
  - name: pbs-ping
    <<: *pbs-direct-api-template
    url: "https://pbs.vm.xbhl.intranet:8007/api2/json/ping"
    conditions:
    - "[STATUS] == 200"
    - "[BODY].data.pong == true"

  - name: pbs-hard-drive-space-check
    <<: *pbs-direct-api-template
    url: "https://pbs.vm.xbhl.intranet:8007/api2/json/nodes/pbs/status"
    conditions:
    - "[STATUS] == 200"
    - "[BODY].data.root.avail > 50000000000" # expected to keep at least ~5% free space

  - name: pbs-main-gateway-status
    group: proxmox
    interval: 30s    
    headers:
      Authorization: "PVEAPIToken=${PVE_API_TOKEN}"
    url: "https://pve.intranet.xbhl.online/api2/json/nodes"
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"