services:
  gatus:
    image: ghcr.io/twin/gatus:${GATUS_VERSION}
    container_name: gatus
    hostname: gatus.ctr.xbhl.intranet
    environment:
      - GATUS_DOMAIN=${GATUS_DOMAIN:?err}
      - GATUS_CONFIG_PATH=/config
      - GATUS_LOG_LEVEL=INFO
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - GITLAB_STATUS_TOKEN=${GITLAB_STATUS_TOKEN:?err}
    volumes:
      - config:/config
      - bin:/bin:ro
    networks:
      - internal
      - proxy
    ports:
      - "${GATUS_PORT:?err}:8080"
    healthcheck:
      test: ["CMD", "/bin/busybox", "wget", "--quiet", "--spider", "http://127.0.0.1:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus-router.rule=Host(`${GATUS_DOMAIN:?err}`)"
      - "traefik.http.routers.gatus-router.entrypoints=websecure"
      - "traefik.http.routers.gatus-router.tls=true"
      - "traefik.http.routers.gatus-router.service=gatus"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:18.4
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
    restart: unless-stopped

volumes:
  db:
    driver: local

  bin:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./bin

  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./config

networks:
  internal:

  proxy:
    external: true
